create table public.eras (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null
);

create table public.periods (
  id bigint generated by default as identity primary key,
  era_id bigint not null references public.eras (id) on delete cascade,
  name text not null,
  start_year integer not null,
  end_year integer not null,
  summary text not null,
  unique (era_id, name),
  check (end_year >= start_year)
);

create table public.people (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.periods (id) on delete cascade,
  name text not null,
  brief_bio text not null
);

create table public.places (
  id bigint generated by default as identity primary key,
  name text not null unique,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180)
);

create table public.events (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.periods (id) on delete cascade,
  place_id bigint references public.places (id) on delete set null,
  title text not null,
  description text not null,
  event_year integer not null
);

alter table public.eras enable row level security;
alter table public.periods enable row level security;
alter table public.people enable row level security;
alter table public.places enable row level security;
alter table public.events enable row level security;

revoke all on table public.eras, public.periods, public.people, public.places, public.events from anon, authenticated;
grant select on table public.eras, public.periods, public.people, public.places, public.events to anon, authenticated;

create policy "Public history eras are readable"
on public.eras for select
to anon, authenticated
using (true);

create policy "Public history periods are readable"
on public.periods for select
to anon, authenticated
using (true);

create policy "Public history people are readable"
on public.people for select
to anon, authenticated
using (true);

create policy "Public history places are readable"
on public.places for select
to anon, authenticated
using (true);

create policy "Public history events are readable"
on public.events for select
to anon, authenticated
using (true);

insert into public.eras (name, description)
values (
  'الخلافة الراشدة',
  'مرحلة تأسيس الدولة الإسلامية بعد وفاة النبي محمد ﷺ، وتعاقب فيها الخلفاء الراشدون الأربعة بين عامي 632 و661م.'
);

insert into public.periods (era_id, name, start_year, end_year, summary)
select
  eras.id,
  seeded.name,
  seeded.start_year,
  seeded.end_year,
  seeded.summary
from public.eras
cross join (
  values
    ('أبو بكر الصديق', 632, 634, 'مرحلة تثبيت وحدة الدولة ومواجهة حروب الردة، وبدء جمع القرآن في مصحف واحد.'),
    ('عمر بن الخطاب', 634, 644, 'مرحلة اتساع الدولة وتنظيم إدارتها، وفيها فُتحت مناطق واسعة من العراق والشام ومصر.'),
    ('عثمان بن عفان', 644, 656, 'مرحلة استمرار الفتوحات وتوحيد المصاحف على قراءة جامعة أُرسلت نسخ منها إلى الأمصار.'),
    ('علي بن أبي طالب', 656, 661, 'مرحلة واجهت اضطرابات سياسية داخلية، واتخذت فيها الكوفة مركزًا لإدارة الخلافة.')
) as seeded (name, start_year, end_year, summary)
where eras.name = 'الخلافة الراشدة';

insert into public.people (period_id, name, brief_bio)
select periods.id, seeded.name, seeded.brief_bio
from (
  values
    ('أبو بكر الصديق', 'أبو بكر الصديق', 'أول الخلفاء الراشدين وأحد أوائل من آمنوا بالإسلام. حافظ على وحدة الدولة بعد وفاة النبي ﷺ، وقاد مواجهة حروب الردة وبدأ مشروع جمع القرآن.'),
    ('عمر بن الخطاب', 'عمر بن الخطاب', 'ثاني الخلفاء الراشدين، عُرف بالحزم والعدل وتطوير مؤسسات الإدارة والقضاء. شهد عهده توسعًا كبيرًا للدولة في العراق والشام ومصر.'),
    ('عثمان بن عفان', 'عثمان بن عفان', 'ثالث الخلفاء الراشدين ومن السابقين إلى الإسلام. ارتبط عهده باستمرار الفتوحات وجمع المسلمين على مصحف موحّد وإرسال نسخه إلى الأمصار.'),
    ('علي بن أبي طالب', 'علي بن أبي طالب', 'رابع الخلفاء الراشدين وابن عم النبي ﷺ وصهره. تولى الخلافة في ظرف سياسي مضطرب، ونقل مركز الحكم إلى الكوفة وعمل على إدارة الخلافات الداخلية.')
) as seeded (period_name, name, brief_bio)
join public.periods on periods.name = seeded.period_name;

insert into public.places (name, lat, lng)
values
  ('المدينة المنورة', 24.4672, 39.6111),
  ('اليمامة', 24.1845, 47.3120),
  ('القادسية', 31.7900, 44.6900),
  ('القدس', 31.7683, 35.2137),
  ('البصرة', 30.5085, 47.7804),
  ('الكوفة', 32.0300, 44.4000);

insert into public.events (period_id, place_id, title, description, event_year)
select periods.id, places.id, seeded.title, seeded.description, seeded.event_year
from (
  values
    ('أبو بكر الصديق', 'المدينة المنورة', 'بدء جمع القرآن', 'بدأ جمع القرآن في مصحف واحد بعد استشهاد عدد من القرّاء في حروب الردة.', 633),
    ('أبو بكر الصديق', 'اليمامة', 'معركة اليمامة', 'كانت من أبرز معارك حروب الردة وأسهمت نتائجها في تثبيت وحدة الدولة.', 633),
    ('عمر بن الخطاب', 'القادسية', 'معركة القادسية', 'انتهت بانتصار جيش المسلمين ومهّدت لفتح المدائن وتراجع نفوذ الدولة الساسانية في العراق.', 636),
    ('عمر بن الخطاب', 'القدس', 'تسلّم القدس', 'وصل عمر بن الخطاب إلى القدس وتسلم مفاتيحها بعد اتفاق أهلها على الصلح.', 638),
    ('عثمان بن عفان', 'المدينة المنورة', 'توحيد المصاحف', 'نُسخت مصاحف معتمدة وأُرسلت إلى الأمصار لتوحيد القراءة والحد من الاختلاف.', 650),
    ('علي بن أبي طالب', 'البصرة', 'وقعة الجمل', 'وقعت قرب البصرة في سياق الخلافات السياسية التي شهدتها بداية خلافة علي بن أبي طالب.', 656)
) as seeded (period_name, place_name, title, description, event_year)
join public.periods on periods.name = seeded.period_name
join public.places on places.name = seeded.place_name;
